version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8501:8501"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - '8890:80'
    restart: always
    depends_on:
      - db